export const classes = ['apple', 
           'banana',
           'cat',
           'dog',
           'elephant',
           'fish',
           'guitar',
           'hot air balloon',
           'house plant',
           'key',
           'lightning',
           'mountain',
           'nail',
           'owl',
           'palm tree',
           'pencil',
           'rhinoceros',
           'snake',
           'the eiffel tower',
           'umbrella',
           'vase',
           'watermelon',
           'zigzag'
          ]